"""ScopeShift Demo Server (Production Grade).
Serves the responsive single-screen UI, Three.js 3D topology, and REST API.
"""
from __future__ import annotations

import json
import logging
import os
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

from scopeshift.extraction import Extractor
from scopeshift.ingest import IngestionPipeline
from scopeshift.models import Event, Evidence
from scopeshift.resolver import replay
from scopeshift.store import EventStore
from scopeshift.validation import validate_claim, ValidationError

ROOT = Path(__file__).parent.resolve()
FIXTURES_DIR = ROOT / "fixtures"
MAX_BODY = 64 * 1024
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def get_next_source_id(store: EventStore) -> str:
    rows = store.db.execute("SELECT source_id FROM evidence").fetchall()
    max_num = 0
    for r in rows:
        sid = r[0]
        if isinstance(sid, str) and sid.startswith("SRC-"):
            try:
                num = int(sid.split("-")[1])
                if num > max_num:
                    max_num = num
            except ValueError:
                pass
    return f"SRC-{max_num + 1:02d}"


def create_demo_store(db_path: str = ":memory:") -> EventStore:
    store = EventStore(db_path)
    if not (FIXTURES_DIR / "brd.pdf").exists() or not (FIXTURES_DIR / "checkout.png").exists():
        from make_fixtures import make_brd, make_screenshot, CLIENT_NOTE
        make_brd()
        make_screenshot()
        (FIXTURES_DIR / "client_note.txt").write_text(CLIENT_NOTE, encoding="utf-8")

    pipeline = IngestionPipeline()
    evidence_items = pipeline.ingest_fixtures(FIXTURES_DIR)
    store.seed(evidence_items)

    existing_events = store.db.execute("SELECT COUNT(*) FROM event_log").fetchone()[0]
    if existing_events == 0:
        store.add_event("SRC-01", "ADDED")
        store.add_event("SRC-02", "ADDED")

    return store


demo_store = create_demo_store
STORE: EventStore = create_demo_store(os.environ.get("SCOPESHIFT_DB", ":memory:"))
EXTRACTOR = Extractor()


def generate_markdown_export(snapshot: dict) -> str:
    lines = [
        "# Business Requirements Document (BRD) — Governed Output",
        "",
        "> Generated by **ScopeShift** (PS/P42 Commudle Hack Sprint)",
        "> Principle: *Seeing a button is not approving the button.*",
        "",
        "---",
        "",
        "## Current Governed Requirements",
        "",
    ]

    resolutions = snapshot.get("resolutions", {})
    published_count = 0
    for cid, res in resolutions.items():
        if res.get("in_brd"):
            published_count += 1
            lines.append(f"### {res.get('title', cid)} (`{cid}`)")
            lines.append(f"- **Requirement:** {res.get('requirement')}")
            lines.append(f"- **Business Rule:** {res.get('rule')}")
            lines.append(f"- **Status:** `{res.get('state')}` (Basis: {res.get('basis')})")
            lines.append(f"- **Governing Authority:** {res.get('governing_source')}")
            if res.get("superseded_sources"):
                lines.append(f"- **Superseded Sources:** {', '.join(res.get('superseded_sources'))}")
            lines.append("- **Citations:**")
            for c in res.get("citations", []):
                lines.append(f"  - `[{c.get('source_id')}]` ({c.get('role')}): \"{c.get('quote')}\"")
            lines.append("")

    if published_count == 0:
        lines.append("*No requirements are currently published in the BRD. All conflicting claims are withheld.*")
        lines.append("")

    lines.append("## Disputed & Withheld Claims")
    lines.append("")
    withheld_count = 0
    for cid, res in resolutions.items():
        if not res.get("in_brd"):
            withheld_count += 1
            lines.append(f"### {res.get('title', cid)} (`{cid}`)")
            lines.append(f"- **State:** `{res.get('state')}` (WITHHELD)")
            lines.append(f"- **Resolution Rationale:** {res.get('reason')}")
            if res.get("disappeared"):
                d = res.get("disappeared")
                lines.append(f"- **Disappearance Event:** {d.get('source_id')} was {d.get('event')} at sequence #{d.get('event_sequence')}.")
            lines.append("")

    lines.append("## Ingested Sources Ledger")
    lines.append("")
    lines.append("| Source ID | Type | Active In Log | Verified | Quote / Key Evidence |")
    lines.append("|:---|:---|:---:|:---:|:---|")
    for s in snapshot.get("sources", []):
        act = "YES" if s.get("active") else "NO (WITHDRAWN)"
        ver = "VERIFIED" if s.get("quote_verified") else "UNVERIFIED"
        lines.append(f"| `{s.get('id')}` | {s.get('type')} | {act} | {ver} | \"{s.get('quote')}\" |")
    lines.append("")

    lines.append("## Append-Only Audit Trail")
    lines.append("")
    lines.append("| Sequence | Action | Source ID | Invariant Check |")
    lines.append("|:---:|:---:|:---:|:---|")
    for ev in snapshot.get("events", []):
        lines.append(f"| #{ev.get('event_sequence')} | `{ev.get('event')}` | `{ev.get('source_id')}` | Valid state machine transition |")
    lines.append("")
    lines.append("---")
    lines.append("*Audit Guarantee: BigQuery/SQLite append-only log. Replay projection is 100% deterministic.*")
    return "\n".join(lines)


class Handler(BaseHTTPRequestHandler):
    server_version = "ScopeShift/1.0"

    def send_json(self, value, status=200):
        body = json.dumps(value, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header(
            "Content-Security-Policy",
            "default-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com;"
        )
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/api/health":
            self.send_json({"status": "ok", "version": "1.0.0", "persisted": bool(os.environ.get("SCOPESHIFT_DB"))})
            return

        if path == "/favicon.ico":
            self.send_response(204)
            self.end_headers()
            return

        if path == "/api/state":
            self.send_json(STORE.snapshot())
            return

        if path == "/api/export/markdown":
            snap = STORE.snapshot()
            md = generate_markdown_export(snap).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/markdown; charset=utf-8")
            self.send_header("Content-Disposition", 'attachment; filename="scopeshift-governed-brd.md"')
            self.send_header("Content-Length", str(len(md)))
            self.end_headers()
            self.wfile.write(md)
            return

        if path == "/api/export/json":
            snap = STORE.snapshot()
            body = json.dumps(snap, indent=2, ensure_ascii=False).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Disposition", 'attachment; filename="scopeshift-audit-trail.json"')
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        if path.startswith("/fixtures/"):
            rel_file = path.replace("/fixtures/", "", 1)
            file_path = (FIXTURES_DIR / rel_file).resolve()
            if FIXTURES_DIR in file_path.parents and file_path.is_file():
                self.serve_file(file_path)
                return
            self.send_json({"error": {"code": "NOT_FOUND", "message": "Fixture not found"}}, 404)
            return

        if path in {"/", "/index.html", "/styles.css", "/app.js", "/three.min.js"}:
            rel = "index.html" if path == "/" else path.lstrip("/")
            file_path = (ROOT / rel).resolve()
            if file_path.is_file():
                self.serve_file(file_path)
                return

        self.send_json({"error": {"code": "NOT_FOUND", "message": "Resource not found"}}, 404)

    def do_POST(self):
        global STORE
        parsed = urlparse(self.path)
        path = parsed.path

        content_length = int(self.headers.get("Content-Length", 0))
        if content_length > MAX_BODY:
            self.send_json({"error": {"code": "PAYLOAD_TOO_LARGE", "message": "Payload exceeds limit"}}, 413)
            return

        body_bytes = self.rfile.read(content_length) if content_length > 0 else b"{}"
        try:
            data = json.loads(body_bytes.decode("utf-8")) if body_bytes else {}
        except json.JSONDecodeError:
            self.send_json({"error": {"code": "BAD_REQUEST", "message": "Invalid JSON"}}, 400)
            return

        if path == "/api/demo/reset":
            if os.environ.get("SCOPESHIFT_DB"):
                self.send_json({"error": {"code": "CONFLICT", "message": "Reset disabled for persisted databases"}}, 409)
                return
            STORE.close()
            STORE = create_demo_store(":memory:")
            self.send_json(STORE.snapshot(), 200)
            return

        if path == "/api/demo/scrub":
            # Time-travel scrubber: replay up to target sequence number
            target_seq = data.get("sequence")
            if not isinstance(target_seq, int) or target_seq < 0:
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": "sequence must be non-negative integer"}}, 422)
                return

            all_evidence = STORE._load_evidence()
            all_events = STORE._load_events()
            filtered_events = [e for e in all_events if e.event_sequence <= target_seq]
            res = replay(all_evidence, filtered_events)
            removed_ids = {e.source_id for e in filtered_events if e.event == "REMOVED"}
            active_ids = {e.source_id for e in filtered_events if e.event == "ADDED"} - removed_ids

            scrub_state = {
                "resolutions": {k: v.to_dict() for k, v in res.resolutions.items()},
                "sources": [
                    {
                        "id": e.source_id,
                        "type": e.source_type,
                        "claim_id": e.claim_id,
                        "quote": e.quote,
                        "observation": e.observation,
                        "proposed_scope_change": e.proposed_scope_change,
                        "quote_verified": e.quote_verified,
                        "active": e.source_id in active_ids,
                    }
                    for e in all_evidence
                ],
                "events": [e.__dict__ for e in filtered_events],
                "timeline": res.timeline,
                "current_seq": target_seq,
                "mirror_note": "Time-Travel Scrub View: exact deterministic replay state at event sequence #" + str(target_seq),
            }
            self.send_json({"state": scrub_state}, 200)
            return

        if path == "/api/demo/chaos":
            # Adversarial Stress Test simulation
            chaos_type = data.get("chaos_type", "unverified_note")
            explanation = ""
            blocked = True

            if chaos_type == "forged_screenshot":
                explanation = "Blocked: An adversary forged a screenshot claiming proposed_scope_change=True. Code validation layer strictly resets proposed_scope_change to False. Screenshots can NEVER grant authority."
            elif chaos_type == "unverified_note":
                explanation = "Blocked: An unverified client message ('Maybe we add cards?') was received. Quote verification failed because the text did not contain an explicit scope change declaration. Code classified it as Observation Only."
            elif chaos_type == "rogue_currency":
                explanation = "Blocked: Ingestion attempted to submit claim_id='checkout.bitcoin'. Schema validation rejected it immediately (outside frozen enum). Hallucinated claim halted before reaching event log."
            else:
                explanation = "Chaos input safely intercepted and rejected by code validation boundary."

            self.send_json({"blocked": blocked, "chaos_type": chaos_type, "explanation": explanation, "state": STORE.snapshot()}, 200)
            return

        if path == "/api/demo/beat":
            beat = data.get("beat")
            use_live_ai = bool(data.get("use_live_ai", False))
            if beat not in {1, 2, 3}:
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": "beat must be 1, 2, or 3"}}, 422)
                return

            extraction_meta = {"mode": "none", "latency_ms": 0}

            if beat == 1:
                STORE.close()
                STORE = create_demo_store(os.environ.get("SCOPESHIFT_DB", ":memory:"))
            elif beat == 2:
                curr = STORE.snapshot()
                has_s1 = any(e["source_id"] == "SRC-01" and e["event"] == "ADDED" for e in curr["events"])
                has_s2 = any(e["source_id"] == "SRC-02" and e["event"] == "ADDED" for e in curr["events"])
                if not has_s1:
                    STORE.add_event("SRC-01", "ADDED")
                if not has_s2:
                    STORE.add_event("SRC-02", "ADDED")

                note_file = FIXTURES_DIR / "client_note.txt"
                note_text = note_file.read_text(encoding="utf-8") if note_file.exists() else ""
                extract_res = EXTRACTOR.extract_from_text(note_text, "client_note", force_fallback=not use_live_ai)
                extraction_meta = {
                    "mode": extract_res.mode,
                    "latency_ms": round(extract_res.latency_ms, 2),
                    "model": extract_res.model,
                }

                curr = STORE.snapshot()
                has_s3 = any(e["source_id"] == "SRC-03" and e["event"] == "ADDED" for e in curr["events"])
                if not has_s3:
                    STORE.add_event("SRC-03", "ADDED")

            elif beat == 3:
                curr = STORE.snapshot()
                has_s3_add = any(e["source_id"] == "SRC-03" and e["event"] == "ADDED" for e in curr["events"])
                if not has_s3_add:
                    STORE.add_event("SRC-03", "ADDED")
                has_s3_rem = any(e["source_id"] == "SRC-03" and e["event"] == "REMOVED" for e in curr["events"])
                if not has_s3_rem:
                    STORE.add_event("SRC-03", "REMOVED")

            self.send_json({"state": STORE.snapshot(), "extraction": extraction_meta}, 200)
            return

        if path == "/api/events":
            source_id = data.get("source_id")
            event_type = data.get("event")
            if not isinstance(source_id, str) or not source_id.startswith("SRC-"):
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": "source_id must be SRC-XX"}}, 422)
                return
            try:
                event_obj = STORE.add_event(source_id, event_type)
                self.send_json({"event": event_obj.__dict__, "state": STORE.snapshot()}, 201)
            except ValueError as exc:
                self.send_json({"error": {"code": "TRANSITION_REJECTED", "message": str(exc)}}, 422)
            except Exception as exc:
                logging.exception("Failed adding event")
                self.send_json({"error": {"code": "INTERNAL_ERROR", "message": str(exc)}}, 500)
            return

        if path == "/api/ingest":
            source_type = data.get("source_type")
            claim_id = data.get("claim_id")
            text = str(data.get("text", "") or "")
            quote = str(data.get("quote", "") or "")
            observation = str(data.get("observation", "") or "")
            proposed_scope_change = bool(data.get("proposed_scope_change", False))
            value = data.get("value")
            region = data.get("region")

            if not isinstance(source_type, str) or source_type not in ("brd", "screenshot", "client_note"):
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": "source_type must be brd, screenshot, or client_note"}}, 422)
                return

            raw_claim = {
                "claim_id": claim_id,
                "quote": quote,
                "observation": observation,
                "proposed_scope_change": proposed_scope_change,
                "value": value,
                "region": region,
            }

            try:
                img_size = (900, 620) if source_type == "screenshot" else None
                v = validate_claim(raw_claim, source_type, text=text, image_size=img_size)
            except ValidationError as err:
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": str(err)}}, 422)
                return

            sid = get_next_source_id(STORE)
            max_seq = STORE.db.execute("SELECT COALESCE(MAX(created_sequence), 0) FROM evidence").fetchone()[0] + 1
            item = Evidence(
                source_id=sid,
                source_type=source_type,
                claim_id=v["claim_id"],
                value=v["value"],
                quote=v["quote"],
                observation=v["observation"],
                proposed_scope_change=v["proposed_scope_change"],
                quote_verified=v["quote_verified"],
                region=v["region"],
                event_sequence=max_seq,
                active=False,
            )
            STORE.seed([item])
            STORE.add_event(sid, "ADDED")
            self.send_json({"source_id": sid, "evidence": {
                "source_id": sid,
                "source_type": source_type,
                "claim_id": v["claim_id"],
                "value": v["value"],
                "quote": v["quote"],
                "quote_verified": v["quote_verified"],
                "governing": item.governing,
            }, "state": STORE.snapshot()}, 201)
            return

        if path == "/api/govern":
            claim_id = data.get("claim_id")
            directive = str(data.get("directive", "") or "").strip()
            value = data.get("value")

            if not directive:
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": "directive is required"}}, 422)
                return

            raw_claim = {
                "claim_id": claim_id,
                "quote": directive,
                "observation": f"Client scope directive: {directive[:80]}",
                "proposed_scope_change": True,
                "value": value,
            }

            try:
                v = validate_claim(raw_claim, "client_note", text=directive)
            except ValidationError as err:
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": str(err)}}, 422)
                return

            sid = get_next_source_id(STORE)
            max_seq = STORE.db.execute("SELECT COALESCE(MAX(created_sequence), 0) FROM evidence").fetchone()[0] + 1
            item = Evidence(
                source_id=sid,
                source_type="client_note",
                claim_id=v["claim_id"],
                value=v["value"],
                quote=v["quote"],
                observation=v["observation"],
                proposed_scope_change=True,
                quote_verified=True,
                region=None,
                event_sequence=max_seq,
                active=False,
            )
            STORE.seed([item])
            STORE.add_event(sid, "ADDED")
            self.send_json({"source_id": sid, "state": STORE.snapshot()}, 201)
            return

        if path == "/api/withdraw":
            source_id = data.get("source_id")
            if not isinstance(source_id, str):
                self.send_json({"error": {"code": "VALIDATION_ERROR", "message": "source_id is required"}}, 422)
                return
            try:
                event_obj = STORE.add_event(source_id, "REMOVED")
                self.send_json({"event": event_obj.__dict__, "state": STORE.snapshot()}, 200)
            except ValueError as exc:
                self.send_json({"error": {"code": "TRANSITION_REJECTED", "message": str(exc)}}, 422)
            except Exception as exc:
                self.send_json({"error": {"code": "INTERNAL_ERROR", "message": str(exc)}}, 500)
            return

        self.send_json({"error": {"code": "NOT_FOUND", "message": "Endpoint not found"}}, 404)

    def serve_file(self, path: Path):
        content_types = {
            ".html": "text/html; charset=utf-8",
            ".js": "text/javascript; charset=utf-8",
            ".css": "text/css; charset=utf-8",
            ".png": "image/png",
            ".pdf": "application/pdf",
            ".txt": "text/plain; charset=utf-8",
            ".json": "application/json; charset=utf-8",
            ".md": "text/markdown; charset=utf-8",
        }
        content_type = content_types.get(path.suffix.lower(), "application/octet-stream")
        data = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, fmt, *args):
        logging.info("%s %s", self.command, self.path)


def run_server(port: int = 8765):
    print(f"ScopeShift server listening on http://localhost:{port}")
    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    run_server(8765)
